version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - backend_network

  web:
    build: .
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend_network

networks:
  backend_network:

volumes:
  pgdata:
