# Generated by Django 4.2 on 2025-02-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата концерта')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('status', models.CharField(choices=[('upcoming', 'Ожидается'), ('past', 'Прошел')], max_length=10, verbose_name='Статус')),
                ('ticket_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на билеты')),
            ],
        ),
    ]
