# Generated by Django 5.1.6 on 2025-02-27 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('cover', models.URLField(verbose_name='Обложка')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Год выпуска')),
                ('yandex_music_link', models.URLField(verbose_name='Ссылка на трек в Яндекс Музыке')),
            ],
        ),
    ]
